# Don't change this! This allows updated plugins to automatically update your configuration if needed
Configuration-Version: 1

# A list of all blocks to be ignored when generating the model
Ignored-Block-IDs:
  - 0 # Air
  - 95 # Invisible Bedrock
  - 212 # Border Block (PowerNukkit only)